version: '2.1'

services:
    postgresql:
        image: postgres:11
        volumes:
            - "${VOLUME_DUMP}/postgres:/var/lib/postgresql/data"
        environment:
            POSTGRES_USER: "${POSTGRES_USER:-postgres}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
        networks:
            wise_lan:
                ipv4_address: 10.10.10.30
    php:
        build: build/php
        volumes:
            - "${VOLUME_APP}:/var/www/html/app"
        links:
          - "postgresql:db"
        networks:
            wise_lan:
                ipv4_address: 10.10.10.20
    nginx:
        build: build/nginx
        depends_on:
            - php
        volumes:
            - "${VOLUME_APP}:/var/www/html"
            - "${VOLUME_LOGS}/nginx:/var/log/nginx"
            - "./conf/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        networks:
            wise_lan:
                ipv4_address: 10.10.10.10

networks:
    wise_lan:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"
        ipam:
            driver: default
            config:
                - subnet: 10.10.10.0/24
                  gateway: 10.10.10.1
