version: '2.1'

services:
    postgresql:
        image: postgres:11
        volumes:
            - "${VOLUME_DUMP}/postgres:/var/lib/postgresql/data"
        environment:
            POSTGRES_USER: "${POSTGRES_USER:-postgres}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
        ports:
            - "15432:${POSTGRES_PORT}"
    php:
        build: build/php
        ports:
            - "9000:${PHP_FPM_PORT}"
        volumes:
            - "${VOLUME_APP}:/var/www/html/app"
        links:
          - postgresql
    nginx:
        image: nginx:stable
        depends_on:
            - php
        volumes:
            - "${VOLUME_APP}:/var/www/html"
            - "${VOLUME_LOGS}/nginx:/var/log/nginx"
            - "./build/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            #- "${VOLUME_NGINX_SITES}:/etc/nginx/sites-available/"
            #- "${VOLUME_NGINX_SITES}:/etc/nginx/sites-enabled/"
        ports:
            - "10080:${NGINX_PORT_HTTP}"
            - "10443:${NGINX_PORT_HTTPS}"
